version: '3.7'

volumes:
  php:

networks:
  backend:
    driver: bridge

services:
  php:
    container_name: ${COMPOSE_PROJECT_NAME:-Docker}.php
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    ports:
      - "${COMPOSE_PROJECT_PORT_PHP:-80}:80"
    environment:
      XDEBUG_CONFIG: remote_host=${host_docker_internal:-host.docker.internal}
      PHP_IDE_CONFIG: serverName=phpstorm
    volumes:
      - ./src:/var/www/html
      - ./docker/php/apache:/etc/apache2/sites-available/
    networks:
      - backend
  mysql:
      image: mysql:5.6
      container_name: ${COMPOSE_PROJECT_NAME:-Docker}.mysql
      ports:
         - "${COMPOSE_PROJECT_PORT_MYSQL:-3306}:3306"
      volumes:
          - ./docker/mysql/data:/var/lib/mysql
          - ./docker/mysql/bootstrap.sql:/docker-entrypoint-initdb.d/bootstrap.sql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootroot
      networks:
        - backend
  composer:
    container_name: ${COMPOSE_PROJECT_NAME:-Docker}.composer
    image: composer:latest
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html


